import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'zh' | 'es' | 'ar' | 'id' | 'pt' | 'fr' | 'ja' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    notes: 'NOTES',
    aiChat: 'AI CHAT',
    createTaskList: 'Create Task List',
    taskListTitle: 'Task List Title',
    enterTitle: 'Enter title...',
    addTask: 'Add Task',
    enterTask: 'Enter task...',
    create: 'Create',
    level: 'Level',
    experience: 'Experience',
    levelUp: 'LEVEL UP!',
    markCompleted: 'Mark as Completed',
    deleteTask: 'Delete Task',
    deleteList: 'Delete List',
    completed: 'Completed',
    video: 'Video',
    askAI: 'Ask AI to create task lists for you...',
    send: 'Send',
    createdTaskList: '✅ Created task list',
    withTasks: 'with',
    tasks: 'tasks',
    forYou: 'for you!',
    chatSubtitle: 'Get help organizing your thoughts and tasks',
    chatWelcomeTitle: 'What do you need to organize today?',
    chatWelcomeSubtitle: 'I can help you create structured task lists and organize your thoughts',
    thinking: 'Thinking...',
    connectionError: 'I\'m having trouble connecting right now. Please try again in a moment.',
    suggestion1: 'Create a task list about daily productivity habits',
    chooseNoteType: 'Choose Note Type',
    emptyNote: 'EMPTY',
    emptyNoteDesc: 'Free-form notepad for writing',
    createChecklist: 'CHECKLIST', 
    createChecklistDesc: 'Structured task list',
    save: 'Save',
    cancel: 'Cancel',
    add: 'Add',
    normalText: 'Normal text',
    largeHeading: 'Large heading',
    mediumHeading: 'Medium heading', 
    smallHeading: 'Small heading',
    createSubpage: 'Create subpage',
    insertIntoPage: 'Insert into page',
    bulletList: 'Bullet list',
    numberedList: 'Numbered list',
    taskList: 'Task list',
    toggleList: 'Toggle list',
    codeBlock: 'Code block',
    highlightedQuote: 'Highlighted quote',
    insertDivider: 'Insert divider',
    highlightBlock: 'Highlight block',
    textColors: 'Text colors',
    close: 'Close',
    suggestion2: 'Build a study routine for learning programming',
    suggestion3: 'Organize my morning routine for better focus',
    suggestion4: 'Plan a workout schedule for this week',
    loginTitle: 'Welcome to Mind Notes',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    emailPlaceholder: 'your@example.com',
    passwordPlaceholder: '••••••••',
    signInButton: 'Sign In',
    signUpButton: 'Sign Up',
    signInWithSocial: 'Sign in with {provider}',
    signUpWithSocial: 'Sign up with {provider}',
    alreadyHaveAccount: 'Already have an account? Sign In',
    dontHaveAccount: 'Don\'t have an account? Sign Up',
    forgotPassword: 'Forgot your password?',
    sendResetInstructions: 'Send reset instructions',
    logout: 'Logout',
    logoutSuccess: 'Logged out successfully!',
    logoutError: 'Failed to log out. Please try again.',
  },
  zh: {
    notes: '笔记',
    aiChat: 'AI 聊天',
    createTaskList: '创建任务列表',
    taskListTitle: '任务列表标题',
    enterTitle: '输入标题...',
    addTask: '添加任务',
    enterTask: '输入任务...',
    create: '创建',
    level: '等级',
    experience: '经验',
    levelUp: '升级了！',
    markCompleted: '标记为已完成',
    deleteTask: '删除任务',
    deleteList: '删除列表',
    completed: '已完成',
    video: '视频',
    askAI: '让AI为您创建任务列表...',
    send: '发送',
    createdTaskList: '✅ 已创建任务列表',
    withTasks: '包含',
    tasks: '个任务',
    forYou: '！',
    chatSubtitle: '帮助您整理思路和任务',
    chatWelcomeTitle: '今天您需要整理什么？',
    chatWelcomeSubtitle: '我可以帮助您创建结构化的任务列表并整理思路',
    thinking: '思考中...',
    connectionError: '现在连接有问题，请稍后再试。',
    suggestion1: '创建关于日常生产力习惯的任务列表',
    suggestion2: '制定编程学习例程',
    suggestion3: '整理我的晨间例程以更好地专注',
    suggestion4: '规划本周的锻炼计划',
    chooseNoteType: '选择笔记类型',
    emptyNote: '空白',
    emptyNoteDesc: '自由书写笔记本',
    createChecklist: '清单',
    createChecklistDesc: '结构化任务列表',
    save: '保存',
    cancel: '取消',
    add: '添加',
    normalText: '普通文本',
    largeHeading: '大标题',
    mediumHeading: '中标题',
    smallHeading: '小标题',
    createSubpage: '创建子页面',
    insertIntoPage: '插入到页面',
    bulletList: '项目符号列表',
    numberedList: '编号列表',
    taskList: '任务列表',
    toggleList: '切换列表',
    codeBlock: '代码块',
    highlightedQuote: '高亮引用',
    insertDivider: '插入分隔线',
    highlightBlock: '高亮块',
    textColors: '文本颜色',
    close: '关闭',
    loginTitle: '欢迎来到 Mind Notes',
    emailLabel: '电子邮件',
    passwordLabel: '密码',
    emailPlaceholder: 'your@example.com',
    passwordPlaceholder: '••••••••',
    signInButton: '登录',
    signUpButton: '注册',
    signInWithSocial: '使用 {provider} 登录',
    signUpWithSocial: '使用 {provider} 注册',
    alreadyHaveAccount: '已有账户？登录',
    dontHaveAccount: '没有账户？注册',
    forgotPassword: '忘记密码？',
    sendResetInstructions: '发送重置说明',
    logout: '退出',
    logoutSuccess: '成功退出！',
    logoutError: '退出失败。请重试。',
  },
  es: {
    notes: 'NOTAS',
    aiChat: 'CHAT IA',
    createTaskList: 'Crear Lista de Tareas',
    taskListTitle: 'Título de Lista de Tareas',
    enterTitle: 'Ingresa título...',
    addTask: 'Agregar Tarea',
    enterTask: 'Ingresa tarea...',
    create: 'Crear',
    level: 'Nivel',
    experience: 'Experiencia',
    levelUp: '¡SUBISTE DE NIVEL!',
    markCompleted: 'Marcar como Completado',
    deleteTask: 'Eliminar Tarea',
    deleteList: 'Eliminar Lista',
    completed: 'Completado',
    video: 'Video',
    askAI: 'Pide a la IA que cree listas de tareas para ti...',
    send: 'Enviar',
    createdTaskList: '✅ Lista de tareas creada',
    withTasks: 'con',
    tasks: 'tareas',
    forYou: 'para ti!',
    chatSubtitle: 'Obtén ayuda organizando tus pensamientos y tareas',
    chatWelcomeTitle: '¿Qué necesitas organizar hoy?',
    chatWelcomeSubtitle: 'Puedo ayudarte a crear listas de tareas estructuradas y organizar tus pensamientos',
    thinking: 'Pensando...',
    connectionError: 'Tengo problemas de conexión ahora. Inténtalo de nuevo en un momento.',
    suggestion1: 'Crear una lista de tareas sobre hábitos de productividad diarios',
    suggestion2: 'Construir una rutina de estudio para aprender programación',
    suggestion3: 'Organizar mi rutina matutina para mejor enfoque',
    suggestion4: 'Planificar un horario de ejercicios para esta semana',
    chooseNoteType: 'Elegir Tipo de Nota',
    emptyNote: 'VACÍA',
    emptyNoteDesc: 'Bloc de notas libre',
    createChecklist: 'LISTA',
    createChecklistDesc: 'Lista de tareas estructurada',
    save: 'Guardar',
    cancel: 'Cancelar',
    add: 'Añadir',
    normalText: 'Texto normal',
    largeHeading: 'Título grande',
    mediumHeading: 'Título mediano',
    smallHeading: 'Título pequeño',
    createSubpage: 'Crear subpágina',
    insertIntoPage: 'Insertar en página',
    bulletList: 'Lista con viñetas',
    numberedList: 'Lista numerada',
    taskList: 'Lista de tareas',
    toggleList: 'Lista desplegable',
    codeBlock: 'Bloque de código',
    highlightedQuote: 'Cita destacada',
    insertDivider: 'Insertar divisor',
    highlightBlock: 'Bloque destacado',
    textColors: 'Colores de texto',
    close: 'Cerrar',
    loginTitle: 'Bienvenido a Mind Notes',
    emailLabel: 'Correo electrónico',
    passwordLabel: 'Contraseña',
    emailPlaceholder: 'tu@ejemplo.com',
    passwordPlaceholder: '••••••••',
    signInButton: 'Iniciar sesión',
    signUpButton: 'Registrarse',
    signInWithSocial: 'Iniciar sesión con {provider}',
    signUpWithSocial: 'Registrarse con {provider}',
    alreadyHaveAccount: '¿Ya tienes una cuenta? Inicia sesión',
    dontHaveAccount: '¿No tienes una cuenta? Regístrate',
    forgotPassword: '¿Olvidaste tu contraseña?',
    sendResetInstructions: 'Enviar instrucciones de restablecimiento',
    logout: 'Cerrar sesión',
    logoutSuccess: '¡Sesión cerrada exitosamente!',
    logoutError: 'Error al cerrar sesión. Por favor, inténtalo de nuevo.',
  },
  ar: {
    notes: 'الملاحظات',
    aiChat: 'دردشة الذكاء الاصطناعي',
    createTaskList: 'إنشاء قائمة مهام',
    taskListTitle: 'عنوان قائمة المهام',
    enterTitle: 'أدخل العنوان...',
    addTask: 'إضافة مهمة',
    enterTask: 'أدخل المهمة...',
    create: 'إنشاء',
    level: 'المستوى',
    experience: 'الخبرة',
    levelUp: 'ارتقيت في المستوى!',
    markCompleted: 'تمييز كمكتمل',
    deleteTask: 'حذف المهمة',
    deleteList: 'حذف القائمة',
    completed: 'مكتمل',
    video: 'فيديو',
    askAI: 'اطلب من الذكاء الاصطناعي إنشاء قوائم المهام لك...',
    send: 'إرسال',
    createdTaskList: '✅ تم إنشاء قائمة المهام',
    withTasks: 'تحتوي على',
    tasks: 'مهام',
    forYou: 'لك!',
    chatSubtitle: 'احصل على مساعدة في تنظيم أفكارك ومهامك',
    chatWelcomeTitle: 'ما الذي تحتاج لتنظيمه اليوم؟',
    chatWelcomeSubtitle: 'يمكنني مساعدتك في إنشاء قوائم مهام منظمة وتنظيم أفكارك',
    thinking: 'أفكر...',
    connectionError: 'أواجه مشكلة في الاتصال الآن. يرجى المحاولة مرة أخرى لاحقاً.',
    suggestion1: 'إنشاء قائمة مهام حول عادات الإنتاجية اليومية',
    suggestion2: 'بناء روتين دراسي لتعلم البرمجة',
    suggestion3: 'تنظيم روتيني الصباحي لتركيز أفضل',
    suggestion4: 'التخطيط لجدولة التمارين لهذا الأسبوع',
    loginTitle: 'مرحبًا بك في Mind Notes',
    emailLabel: 'البريد الإلكتروني',
    passwordLabel: 'كلمة المرور',
    emailPlaceholder: 'your@example.com',
    passwordPlaceholder: '••••••••',
    signInButton: 'تسجيل الدخول',
    signUpButton: 'التسجيل',
    signInWithSocial: 'تسجيل الدخول باستخدام {provider}',
    signUpWithSocial: 'التسجيل باستخدام {provider}',
    alreadyHaveAccount: 'هل لديك حساب بالفعل؟ تسجيل الدخول',
    dontHaveAccount: 'ليس لديك حساب؟ التسجيل',
    forgotPassword: 'هل نسيت كلمة المرور؟',
    sendResetInstructions: 'إرسال تعليمات إعادة التعيين',
    logout: 'تسجيل الخروج',
    logoutSuccess: 'تم تسجيل الخروج بنجاح!',
    logoutError: 'فشل تسجيل الخروج. يرجى المحاولة مرة أخرى.',
  },
  id: {
    notes: 'CATATAN',
    aiChat: 'CHAT AI',
    createTaskList: 'Buat Daftar Tugas',
    taskListTitle: 'Judul Daftar Tugas',
    enterTitle: 'Masukkan judul...',
    addTask: 'Tambah Tugas',
    enterTask: 'Masukkan tugas...',
    create: 'Buat',
    level: 'Level',
    experience: 'Pengalaman',
    levelUp: 'NAIK LEVEL!',
    markCompleted: 'Tandai Selesai',
    deleteTask: 'Hapus Tugas',
    deleteList: 'Hapus Daftar',
    completed: 'Selesai',
    video: 'Video',
    askAI: 'Minta AI untuk membuat daftar tugas untuk Anda...',
    send: 'Kirim',
    createdTaskList: '✅ Daftar tugas dibuat',
    withTasks: 'dengan',
    tasks: 'tugas',
    forYou: 'untuk Anda!',
    chatSubtitle: 'Dapatkan bantuan mengorganisir pikiran dan tugas Anda',
    chatWelcomeTitle: 'Apa yang perlu Anda organisir hari ini?',
    chatWelcomeSubtitle: 'Saya dapat membantu Anda membuat daftar tugas terstruktur dan mengorganisir pikiran',
    thinking: 'Berpikir...',
    connectionError: 'Saya mengalami masalah koneksi sekarang. Silakan coba lagi nanti.',
    suggestion1: 'Buat daftar tugas tentang kebiasaan produktivitas harian',
    suggestion2: 'Bangun rutina belajar untuk mempelajari pemrograman',
    suggestion3: 'Atur rutina pagi saya untuk fokus yang lebih baik',
    suggestion4: 'Rencanakan jadwal olahraga untuk minggu ini',
    chooseNoteType: 'Pilih Jenis Catatan',
    emptyNote: 'KOSONG',
    emptyNoteDesc: 'Notepad bebas untuk menulis',
    createChecklist: 'DAFTAR',
    createChecklistDesc: 'Daftar tugas terstruktur',
    save: 'Simpan',
    cancel: 'Batal',
    add: 'Tambah',
    normalText: 'Teks normal',
    largeHeading: 'Judul besar',
    mediumHeading: 'Judul sedang',
    smallHeading: 'Judul kecil',
    createSubpage: 'Buat sub-halaman',
    insertIntoPage: 'Sisipkan ke halaman',
    bulletList: 'Daftar bullet',
    numberedList: 'Daftar bernomor',
    taskList: 'Daftar tugas',
    toggleList: 'Daftar toggle',
    codeBlock: 'Blok kode',
    highlightedQuote: 'Kutipan sorotan',
    insertDivider: 'Sisipkan pembagi',
    highlightBlock: 'Blok sorotan',
    textColors: 'Warna teks',
    close: 'Tutup',
    loginTitle: 'Selamat datang di Mind Notes',
    emailLabel: 'Email',
    passwordLabel: 'Kata Sandi',
    emailPlaceholder: 'your@example.com',
    passwordPlaceholder: '••••••••',
    signInButton: 'Masuk',
    signUpButton: 'Daftar',
    signInWithSocial: 'Masuk dengan {provider}',
    signUpWithSocial: 'Daftar dengan {provider}',
    alreadyHaveAccount: 'Sudah punya akun? Masuk',
    dontHaveAccount: 'Belum punya akun? Daftar',
    forgotPassword: 'Lupa kata sandi?',
    sendResetInstructions: 'Kirim instruksi reset',
    logout: 'Keluar',
    logoutSuccess: 'Berhasil keluar!',
    logoutError: 'Gagal keluar. Silakan coba lagi.',
  },
  pt: {
    notes: 'NOTAS',
    aiChat: 'CHAT IA',
    createTaskList: 'Criar Lista de Tarefas',
    taskListTitle: 'Título da Lista de Tarefas',
    enterTitle: 'Digite o título...',
    addTask: 'Adicionar Tarefa',
    enterTask: 'Digite a tarefa...',
    create: 'Criar',
    level: 'Nível',
    experience: 'Experiência',
    levelUp: 'SUBIU DE NÍVEL!',
    markCompleted: 'Marcar como Concluído',
    deleteTask: 'Excluir Tarefa',
    deleteList: 'Excluir Lista',
    completed: 'Concluído',
    video: 'Vídeo',
    askAI: 'Peça para a IA criar listas de tarefas para você...',
    send: 'Enviar',
    createdTaskList: '✅ Criei uma lista de tarefas',
    withTasks: 'com',
    tasks: 'tarefas',
    forYou: 'para você!',
    chatSubtitle: 'Obtenha ajuda organizando seus pensamentos e tarefas',
    chatWelcomeTitle: 'O que você precisa organizar hoje?',
    chatWelcomeSubtitle: 'Posso ajudá-lo a criar listas de tarefas estruturadas e organizar seus pensamentos',
    thinking: 'Pensando...',
    connectionError: 'Estou com problemas de conexão agora. Tente novamente em um momento.',
    suggestion1: 'Criar uma lista de tarefas sobre hábitos de produtividade diários',
    suggestion2: 'Construir uma rotina de estudos para aprender programação',
    suggestion3: 'Organizar minha rotina matinal para melhor foco',
    suggestion4: 'Planejar uma programação de exercícios para esta semana',
    chooseNoteType: 'Escolher Tipo de Nota',
    emptyNote: 'VAZIA',
    emptyNoteDesc: 'Bloco de notas livre para escrever',
    createChecklist: 'LISTA',
    createChecklistDesc: 'Lista de tarefas estruturada',
    save: 'Salvar',
    cancel: 'Cancelar',
    add: 'Adicionar',
    normalText: 'Texto normal',
    largeHeading: 'Título grande',
    mediumHeading: 'Título médio',
    smallHeading: 'Título pequeno',
    createSubpage: 'Criar subpágina',
    insertIntoPage: 'Inserir na página',
    bulletList: 'Lista com marcadores',
    numberedList: 'Lista numerada',
    taskList: 'Lista de tarefas',
    toggleList: 'Lista recolhível',
    codeBlock: 'Bloco de código',
    highlightedQuote: 'Citação destacada',
    insertDivider: 'Inserir divisor',
    highlightBlock: 'Bloco destacado',
    textColors: 'Cores de texto',
    close: 'Fechar',
    loginTitle: 'Bem-vindo ao Mind Notes',
    emailLabel: 'Email',
    passwordLabel: 'Senha',
    emailPlaceholder: 'seu@exemplo.com',
    passwordPlaceholder: '••••••••',
    signInButton: 'Entrar',
    signUpButton: 'Cadastrar',
    signInWithSocial: 'Entrar com {provider}',
    signUpWithSocial: 'Cadastrar com {provider}',
    alreadyHaveAccount: 'Já tem uma conta? Entrar',
    dontHaveAccount: 'Não tem uma conta? Cadastrar',
    forgotPassword: 'Esqueceu sua senha?',
    sendResetInstructions: 'Enviar instruções de redefinição',
    logout: 'Sair',
    logoutSuccess: 'Sessão encerrada com sucesso!',
    logoutError: 'Falha ao sair. Por favor, tente novamente.',
  },
  fr: {
    notes: 'NOTES',
    aiChat: 'CHAT IA',
    createTaskList: 'Créer Liste de Tâches',
    taskListTitle: 'Titre de la Liste de Tâches',
    enterTitle: 'Entrez le titre...',
    addTask: 'Ajouter Tâche',
    enterTask: 'Entrez la tâche...',
    create: 'Créer',
    level: 'Niveau',
    experience: 'Expérience',
    levelUp: 'NIVEAU SUPÉRIEUR!',
    markCompleted: 'Marquer comme Terminé',
    deleteTask: 'Supprimer Tâche',
    deleteList: 'Supprimer Liste',
    completed: 'Terminé',
    video: 'Vidéo',
    askAI: 'Demandez à l\'IA de créer des listes de tâches pour vous...',
    send: 'Envoyer',
    createdTaskList: '✅ Liste de tâches créée',
    withTasks: 'avec',
    tasks: 'tâches',
    forYou: 'pour vous!',
    chatSubtitle: 'Obtenez de l\'aide pour organiser vos pensées et tâches',
    chatWelcomeTitle: 'Que devez-vous organiser aujourd\'hui?',
    chatWelcomeSubtitle: 'Je peux vous aider à créer des listes de tâches structurées et organiser vos pensées',
    thinking: 'Réflexion...',
    connectionError: 'J\'ai des problèmes de connexion maintenant. Veuillez réessayer dans un moment.',
    suggestion1: 'Créer une liste de tâches sur les habitudes de productivité quotidiennes',
    suggestion2: 'Construire une routine d\'étude pour apprendre la programmation',
    suggestion3: 'Organiser ma routine matinale pour un meilleur focus',
    suggestion4: 'Planifier un programme d\'exercices pour cette semaine',
    loginTitle: 'Bienvenue sur Mind Notes',
    emailLabel: 'Email',
    passwordLabel: 'Mot de passe',
    emailPlaceholder: 'votre@exemple.com',
    passwordPlaceholder: '••••••••',
    signInButton: 'Se connecter',
    signUpButton: 'S\'inscrire',
    signInWithSocial: 'Se connecter avec {provider}',
    signUpWithSocial: 'S\'inscrire avec {provider}',
    alreadyHaveAccount: 'Déjà un compte ? Connectez-vous',
    dontHaveAccount: 'Pas de compte ? Inscrivez-vous',
    forgotPassword: 'Mot de passe oublié ?',
    sendResetInstructions: 'Envoyer les instructions de réinitialisation',
    logout: 'Déconnexion',
    logoutSuccess: 'Déconnexion réussie !',
    logoutError: 'Échec de la déconnexion. Veuillez réessayer.',
  },
  ja: {
    notes: 'ノート',
    aiChat: 'AI チャット',
    createTaskList: 'タスクリスト作成',
    taskListTitle: 'タスクリストのタイトル',
    enterTitle: 'タイトルを入力...',
    addTask: 'タスク追加',
    enterTask: 'タスクを入力...',
    create: '作成',
    level: 'レベル',
    experience: '経験値',
    levelUp: 'レベルアップ！',
    markCompleted: '完了にする',
    deleteTask: 'タスク削除',
    deleteList: 'リスト削除',
    completed: '完了',
    video: 'ビデオ',
    askAI: 'AIにタスクリストを作成してもらう...',
    send: '送信',
    createdTaskList: '✅ タスクリストを作成しました',
    withTasks: '',
    tasks: 'つのタスク',
    forYou: 'でした！',
    chatSubtitle: '思考とタスクの整理をお手伝いします',
    chatWelcomeTitle: '今日は何を整理しますか？',
    chatWelcomeSubtitle: '構造化されたタスクリストの作成と思考の整理をお手伝いできます',
    thinking: '考え中...',
    connectionError: '現在接続に問題があります。しばらくしてから再試行してください。',
    suggestion1: '日常の生産性習慣についてのタスクリストを作成',
    suggestion2: 'プログラミング学習のための学習ルーチンを構築',
    suggestion3: 'より良い集中のための朝のルーチンを整理',
    suggestion4: '今週のワークアウトスケジュールを計画',
    loginTitle: 'Mind Notes へようこそ',
    emailLabel: 'メールアドレス',
    passwordLabel: 'パスワード',
    emailPlaceholder: 'your@example.com',
    passwordPlaceholder: '••••••••',
    signInButton: 'ログイン',
    signUpButton: 'サインアップ',
    signInWithSocial: '{provider} でログイン',
    signUpWithSocial: '{provider} でサインアップ',
    alreadyHaveAccount: 'すでにアカウントをお持ちですか？ログイン',
    dontHaveAccount: 'アカウントをお持ちではありませんか？サインアップ',
    forgotPassword: 'パスワードをお忘れですか？',
    sendResetInstructions: 'リセット手順を送信',
    logout: 'ログアウト',
    logoutSuccess: 'ログアウトしました！',
    logoutError: 'ログアウトに失敗しました。もう一度お試しください。',
  },
  ru: {
    notes: 'ЗАМЕТКИ',
    aiChat: 'ИИ ЧАТ',
    createTaskList: 'Создать Список Задач',
    taskListTitle: 'Название Списка Задач',
    enterTitle: 'Введите название...',
    addTask: 'Добавить Задачу',
    enterTask: 'Введите задачу...',
    create: 'Создать',
    level: 'Уровень',
    experience: 'Опыт',
    levelUp: 'ПОВЫШЕНИЕ УРОВНЯ!',
    markCompleted: 'Отметить как Выполненное',
    deleteTask: 'Удалить Задачу',
    deleteList: 'Удалить Список',
    completed: 'Выполнено',
    video: 'Видео',
    askAI: 'Попросите ИИ создать списки задач для вас...',
    send: 'Отправить',
    createdTaskList: '✅ Создан список задач',
    withTasks: 'с',
    tasks: 'задачами',
    forYou: 'для вас!',
    chatSubtitle: 'Получите помощь в организации ваших мыслей и задач',
    chatWelcomeTitle: 'Что вам нужно организовать сегодня?',
    chatWelcomeSubtitle: 'Я могу помочь вам создать структурированные списки задач и организовать мысли',
    thinking: 'Думаю...',
    connectionError: 'У меня проблемы с подключением сейчас. Попробуйте снова через момент.',
    suggestion1: 'Создать список задач о ежедневных привычках продуктивности',
    suggestion2: 'Построить учебную рутину для изучения программирования',
    suggestion3: 'Организовать мою утреннюю рутину для лучшей концентрации',
    suggestion4: 'Спланировать расписание тренировок на эту неделю',
    chooseNoteType: 'Выбрать Тип Заметки',
    emptyNote: 'ПУСТАЯ',
    emptyNoteDesc: 'Свободный блокнот для письма',
    createChecklist: 'СПИСОК',
    createChecklistDesc: 'Структурированный список задач',
    save: 'Сохранить',
    cancel: 'Отмена',
    add: 'Добавить',
    normalText: 'Обычный текст',
    largeHeading: 'Большой заголовок',
    mediumHeading: 'Средний заголовок',
    smallHeading: 'Малый заголовок',
    createSubpage: 'Создать подстраницу',
    insertIntoPage: 'Вставить на страницу',
    bulletList: 'Маркированный список',
    numberedList: 'Нумерованный список',
    taskList: 'Список задач',
    toggleList: 'Переключаемый список',
    codeBlock: 'Блок кода',
    highlightedQuote: 'Выделенная цитата',
    insertDivider: 'Вставить разделитель',
    highlightBlock: 'Выделенный блок',
    textColors: 'Цвета текста',
    close: 'Закрыть',
    loginTitle: 'Добро пожаловать в Mind Notes',
    emailLabel: 'Электронная почта',
    passwordLabel: 'Пароль',
    emailPlaceholder: 'your@example.com',
    passwordPlaceholder: '••••••••',
    signInButton: 'Войти',
    signUpButton: 'Зарегистрироваться',
    signInWithSocial: 'Войти с помощью {provider}',
    signUpWithSocial: 'Зарегистрироваться с помощью {provider}',
    alreadyHaveAccount: 'Уже есть аккаунт? Войти',
    dontHaveAccount: 'Нет аккаунта? Зарегистрироваться',
    forgotPassword: 'Забыли пароль?',
    sendResetInstructions: 'Отправить инструкции по сбросу',
    logout: 'Выйти',
    logoutSuccess: 'Вы успешно вышли!',
    logoutError: 'Не удалось выйти. Пожалуйста, попробуйте еще раз.',
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('pt');

  const t = (key: string): string => {
    const translation = translations[language][key as keyof typeof translations[typeof language]];
    if (translation === undefined) {
      console.warn(`Missing translation for key: ${key} in language: ${language}`);
      return key; // Fallback to key if translation is missing
    }
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};