// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://wyrtlmslvdqtdhcmrygz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5cnRsbXNsdmRxdGRoY21yeWd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5ODc3MjgsImV4cCI6MjA3MzU2MzcyOH0.t2GnI33wBmS2eEMCXJMeWZP2knfVR-mrfG7PdH0BwV0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);